name: Publish Libraries as Packages

on:
  workflow_run:
    workflows: ["Project Build"]
    branches: [ master ]
    types:
      - completed

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish to NuGet Threading
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: OliWorkshop.Threading/OliWorkshop.Threading.csproj
        VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish to NuGet Reactive
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: OliWorkshop.Threading.Reactive/ OliWorkshop.Threading.Reactive.csproj
        VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
        TAG_FORMAT: '*'
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
